spring:
  application:
    name: activity-service   # this will be the service name in Eureka

  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/fitness_activity_db?authSource=admin

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

  instance:
    preferIpAddress: true
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info
