spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness-recommendation
      database: fitness-recommendation
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

  instance:
    preferIpAddress: true
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info
rabbitmq:
  exchange:
    name : fitness.exchange
  queue:
    name : activity.queue
  routing :
    key : activity.tracking
gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}