version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: fitness_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fitness_activity_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
